site_name: Technical Documentation
theme:
  name: readthedocs
  highlightjs: true
nav:
  - Docs:
      - How To Docs: Docs/how_to_docs.md
      - A/V: Docs/av.md
  - Details:
      - About Us: extras/about.md
      - Contact Us: extras/contact.md
